model:
  sa:
    radii:
      - - 0.02
        - 0.04
        - 0.08
      - - 0.04
        - 0.08
        - 0.16
      - - 0.08
        - 0.16
        - 0.32
    centers:
      - 2048
      - 512
      - 128
    mlps:
      - - - 32
          - 32
          - 64
          - 128
        - - 64
          - 64
          - 128
        - - 128
          - 64
          - 96
          - 128
      - - - 64
          - 64
          - 128
          - 256
        - - 128
          - 128
          - 256
        - - 256
          - 128
          - 256
      - - - 64
          - 64
          - 128
          - 256
        - - 128
          - 128
          - 256
        - - 128
          - 128
          - 256
  fp:
    klist:
      - 5
      - 3
      - 3
    nnlist:
      - - 1536
        - 512
        - 256
      - - 1024
        - 512
        - 128
      - - 512
        - 256
        - 128
        - 128
  multi:
    pointnet_out_dim: 131
    out_dims:
      - 1
      - 3
      - 3
      - 1
    ps:
      - 0.5
      - 0.7
      - 0.7
      - 0
gripper_depth: 0.08
loss:
  conf_mult: 1
  add_s_mult: 10
  width_mult: 1
data:
  pc_augm:
    occlusion_nclusters: 0
    occlusion_dropout_rate: 0.0
    sigma: 0.000
    clip: 0.005
  depth_augm:
    sigma: 0.001
    clip: 0.005
    gaussian_kernel: 0
  labels:
    num_pos_contacts: 0
  k: 1
  max_radius: 0.005
  filter_z: True
  z_val: -0.1
  batch_size: 2
  num_points: 2048
train:
  lr: 0.005

